# Generated by Django 3.0.7 on 2020-07-08 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rtsp', models.CharField(max_length=1000)),
                ('area', models.CharField(blank=True, max_length=1000)),
                ('is_demo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('is_demo', models.BooleanField(default=False)),
                ('name_lower', models.CharField(default='<django.db.models.fields.charfield>', max_length=200)),
            ],
            options={
                'unique_together': {('name_lower', 'is_demo')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('labels', models.CharField(max_length=1000, null=True)),
                ('is_relabel', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('uploaded', models.BooleanField(default=False)),
                ('remote_url', models.CharField(max_length=1000, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.CharField(max_length=1000, null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cameras.Image')),
            ],
        ),
    ]
