# Generated by Django 3.0.8 on 2020-08-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("rtsp", models.CharField(max_length=1000)),
                ("area", models.CharField(blank=True, max_length=1000)),
                ("is_demo", models.BooleanField(default=False)),
            ],
        )
    ]
