# Generated by Django 3.0.8 on 2020-09-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cameras", "0002_camera_location")]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="lines",
            field=models.CharField(blank=True, max_length=1000),
        )
    ]
