# Generated by Django 3.0.8 on 2020-10-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0006_auto_20200928_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="send_video_to_cloud",
            field=models.BooleanField(default=False),
        ),
    ]
