# Generated by Django 3.0.8 on 2020-10-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0007_camera_send_video_to_cloud"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="send_video_to_cloud",
        ),
    ]
