# Generated by Django 3.0.8 on 2020-11-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0008_remove_camera_send_video_to_cloud"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="rtsp",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
