# Generated by Django 3.0.8 on 2022-04-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_auto_20201110_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='media_type',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
