# Generated by Django 3.0.7 on 2020-08-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_feed', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoFeed',
        ),
    ]
