# Generated by Django 3.0.8 on 2020-08-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('azure_projects', '0002_remove_project_needretraining'),
        ('inference_modules', '0001_initial'),
        ('locations', '0001_initial'),
        ('azure_parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needRetraining', models.BooleanField(default=True)),
                ('deployed', models.BooleanField(default=False)),
                ('has_configured', models.BooleanField(default=False)),
                ('accuracyRangeMin', models.IntegerField(default=30)),
                ('accuracyRangeMax', models.IntegerField(default=80)),
                ('retraining_counter', models.IntegerField(default=0)),
                ('metrics_is_send_iothub', models.BooleanField(default=False)),
                ('metrics_accuracy_threshold', models.IntegerField(default=50)),
                ('metrics_frame_per_minutes', models.IntegerField(default=6)),
                ('prob_threshold', models.IntegerField(default=10)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.Camera')),
                ('inference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inference_modules.InferenceModule')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('part', models.ManyToManyField(to='azure_parts.Part')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azure_projects.Project')),
            ],
        ),
    ]
