# Generated by Django 3.0.8 on 2020-08-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("azure_part_detections", "0003_auto_20200827_1139")]

    operations = [migrations.RemoveField(model_name="partdetection", name="location")]
