# Generated by Django 3.0.8 on 2020-09-07 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inference_modules', '0001_initial'),
        ('cameras', '0002_camera_location'),
        ('azure_projects', '0003_project_retraining_counter'),
        ('azure_part_detections', '0005_remove_partdetection_retraining_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdetection',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='partdetection',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.Camera'),
        ),
        migrations.AlterField(
            model_name='partdetection',
            name='inference_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inference_modules.InferenceModule'),
        ),
        migrations.AlterField(
            model_name='partdetection',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='azure_projects.Project'),
        ),
    ]
