# Generated by Django 3.0.8 on 2020-09-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_part_detections', '0005_remove_partdetection_retraining_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdetection',
            name='inference_mode',
            field=models.CharField(choices=[('PD', 'part_detection'), ('PC', 'part_counting')], default='PD', max_length=40),
        ),
    ]
