# Generated by Django 3.0.8 on 2020-09-08 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('azure_part_detections', '0008_auto_20200907_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdetection',
            name='deploy_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
