# Generated by Django 3.0.8 on 2020-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0004_camera_danger_zones"),
        ("azure_parts", "0001_initial"),
        ("azure_part_detections", "0011_auto_20200912_2150"),
    ]

    operations = [
        migrations.RemoveField(model_name="pdscenario", name="camera"),
        migrations.AddField(
            model_name="pdscenario",
            name="cameras",
            field=models.ManyToManyField(blank=True, to="cameras.Camera"),
        ),
        migrations.AlterField(
            model_name="pdscenario",
            name="parts",
            field=models.ManyToManyField(blank=True, to="azure_parts.Part"),
        ),
    ]
