# Generated by Django 3.0.8 on 2020-09-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azure_parts", "0001_initial"),
        ("azure_part_detections", "0012_auto_20200914_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partdetection",
            name="parts",
            field=models.ManyToManyField(blank=True, to="azure_parts.Part"),
        ),
    ]
