# Generated by Django 3.0.8 on 2020-10-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "azure_part_detections",
            "0016_remove_partdetection_metrics_accuracy_threshold",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="partdetection",
            name="inference_protocol",
            field=models.CharField(
                choices=[("grpc", "grpc"), ("http", "http")],
                default="http",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="partdetection",
            name="inference_source",
            field=models.CharField(
                choices=[("lva", "lva"), ("capture_module", "capture_module")],
                default="lva",
                max_length=40,
            ),
        ),
    ]
