# Generated by Django 3.0.8 on 2021-08-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cascade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('flow', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('raw_data', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('prediction_uri', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
    ]
