# Generated by Django 3.0.8 on 2021-08-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_cascades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cascade',
            name='screenshot',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
