# Generated by Django 3.0.8 on 2020-08-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("azure_parts", "0001_initial"),
        ("cameras", "0001_initial"),
        ("locations", "0001_initial"),
        ("azure_projects", "0001_initial"),
        ("inference_modules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartDetection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("needRetraining", models.BooleanField(default=True)),
                ("deployed", models.BooleanField(default=False)),
                ("has_configured", models.BooleanField(default=False)),
                ("accuracyRangeMin", models.IntegerField(default=30)),
                ("accuracyRangeMax", models.IntegerField(default=80)),
                ("retraining_counter", models.IntegerField(default=0)),
                ("metrics_is_send_iothub", models.BooleanField(default=False)),
                ("metrics_accuracy_threshold", models.IntegerField(default=50)),
                ("metrics_frame_per_minutes", models.IntegerField(default=6)),
                ("prob_threshold", models.IntegerField(default=10)),
                (
                    "camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cameras.Camera",
                    ),
                ),
                (
                    "inference_module",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inference_modules.InferenceModule",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.Location",
                    ),
                ),
                ("part", models.ManyToManyField(to="azure_parts.Part")),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="azure_projects.Project",
                    ),
                ),
            ],
        )
    ]
