# Generated by Django 3.0.8 on 2020-08-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("azure_part_detections", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="partdetection",
            name="maxImage",
            field=models.IntegerField(default=10),
        )
    ]
