# Generated by Django 3.0.8 on 2020-08-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("azure_part_detections", "0002_partdetection_maximage")]

    operations = [
        migrations.RenameField(
            model_name="partdetection", old_name="part", new_name="parts"
        )
    ]
