# Generated by Django 3.0.8 on 2020-09-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0002_camera_location"),
        ("azure_parts", "0001_initial"),
        ("azure_projects", "0003_project_retraining_counter"),
        ("azure_part_detections", "0006_auto_20200907_0738"),
    ]

    operations = [
        migrations.AddField(
            model_name="partdetection",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="PDScenario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "inference_mode",
                    models.CharField(
                        choices=[("PD", "part_detection"), ("PC", "part_counting")],
                        default="PD",
                        max_length=40,
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cameras.Camera",
                    ),
                ),
                ("parts", models.ManyToManyField(to="azure_parts.Part")),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="azure_projects.Project",
                    ),
                ),
            ],
        ),
    ]
