# Generated by Django 3.0.8 on 2020-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0002_camera_location"),
        ("azure_part_detections", "0007_auto_20200907_0740"),
    ]

    operations = [
        migrations.RemoveField(model_name="partdetection", name="camera"),
        migrations.AddField(
            model_name="partdetection",
            name="cameras",
            field=models.ManyToManyField(blank=True, to="cameras.Camera"),
        ),
    ]
