# Generated by Django 3.0.8 on 2020-09-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("azure_part_detections", "0009_partdetection_deploy_timestamp")]

    operations = [
        migrations.AddField(
            model_name="partdetection",
            name="send_video_to_cloud",
            field=models.BooleanField(default=False),
        )
    ]
