# Generated by Django 3.0.8 on 2020-09-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azure_part_detections", "0014_partdetection_fps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partdetection",
            name="prob_threshold",
            field=models.IntegerField(default=60),
        ),
    ]
