# Generated by Django 3.0.8 on 2020-10-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("azure_part_detections", "0017_auto_20201007_0646"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partdetection",
            name="send_video_to_cloud",
        ),
    ]
