# Generated by Django 3.0.8 on 2020-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azure_part_detections", "0018_remove_partdetection_send_video_to_cloud"),
    ]

    operations = [
        migrations.AddField(
            model_name="partdetection",
            name="disable_video_feed",
            field=models.BooleanField(default=False),
        ),
    ]
