# Generated by Django 3.0.8 on 2020-11-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azure_part_detections", "0019_partdetection_disable_video_feed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partdetection",
            name="fps",
            field=models.FloatField(default=10.0),
        ),
    ]
