# Generated by Django 3.1.4 on 2021-02-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azure_part_detections", "0020_auto_20201111_1002"),
    ]

    operations = [
        migrations.AddField(
            model_name="partdetection",
            name="counting_end_time",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="partdetection",
            name="counting_start_time",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="partdetection",
            name="max_people",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="partdetection",
            name="inference_mode",
            field=models.CharField(
                choices=[
                    ("PD", "part_detection"),
                    ("PC", "part_counting"),
                    ("ES", "employee_safety"),
                    ("DD", "defect_detection"),
                    ("ESA", "empty_shelf_alert"),
                    ("TCC", "total_customer_counting"),
                    ("CQA", "crowded_queue_alert"),
                ],
                default="PD",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="pdscenario",
            name="inference_mode",
            field=models.CharField(
                choices=[
                    ("PD", "part_detection"),
                    ("PC", "part_counting"),
                    ("ES", "employee_safety"),
                    ("DD", "defect_detection"),
                    ("ESA", "empty_shelf_alert"),
                    ("TCC", "total_customer_counting"),
                    ("CQA", "crowded_queue_alert"),
                ],
                default="PD",
                max_length=40,
            ),
        ),
    ]
