# Generated by Django 3.0.8 on 2021-08-20 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azure_cascades', '0001_initial'),
        ('azure_part_detections', '0022_pdscenario_fps'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdetection',
            name='cascade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='azure_cascades.Cascade'),
        ),
        migrations.AddField(
            model_name='partdetection',
            name='deployment_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
