# Generated by Django 3.0.8 on 2021-11-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_part_detections', '0023_auto_20210820_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdetection',
            name='ava_is_send_iothub',
            field=models.BooleanField(default=False),
        ),
    ]
