# Generated by Django 3.0.4 on 2020-04-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_auto_20200416_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='download_uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
