# Generated by Django 3.0.4 on 2020-04-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_auto_20200423_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='device_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='setting',
            name='iot_hub_connection_string',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='setting',
            name='module_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
