# Generated by Django 3.0.8 on 2020-08-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("azure_projects", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "name_lower",
                    models.CharField(
                        default="<django.db.models.fields.charfield>", max_length=200
                    ),
                ),
                (
                    "customvision_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "customvision_type",
                    models.CharField(blank=True, default="Regular", max_length=20),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="azure_projects.Project",
                    ),
                ),
            ],
            options={"unique_together": {("name_lower", "project")}},
        )
    ]
