# Generated by Django 3.0.8 on 2020-08-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azure_training', '0003_remove_project_parts'),
        ('azure_parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azure_training.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name_lower', 'project_id')},
        ),
        migrations.RemoveField(
            model_name='part',
            name='is_demo',
        ),
    ]
