# Generated by Django 3.0.8 on 2021-09-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_parts', '0002_auto_20210914_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='local_image_count',
        ),
        migrations.RemoveField(
            model_name='part',
            name='remote_image_count',
        ),
    ]
