# Generated by Django 3.0.8 on 2020-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notifications", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("project", "project"), ("part_detection", "part_detection")],
                default="project",
                max_length=20,
            ),
        )
    ]
