# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageProcessorGrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ImageProcessorGrpc.proto',
  package='ImageProcessorGrpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18ImageProcessorGrpc.proto\x12\x12ImageProcessorGrpc\"_\n\tImageBody\x12\x10\n\x08\x63\x61meraId\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x15\n\rsmallImageRGB\x18\x05 \x01(\x0c\"\x1b\n\nImageReply\x12\r\n\x05\x65rror\x18\x01 \x01(\t*;\n\x0bPortNumbers\x12\n\n\x06Unused\x10\x00\x12 \n\x1a\x43\x61meraToVideoProcessorPort\x10\xa0\xe2\x01\x32]\n\x0bGrpcChannel\x12N\n\x0bSubmitImage\x12\x1d.ImageProcessorGrpc.ImageBody\x1a\x1e.ImageProcessorGrpc.ImageReply\"\x00\x62\x06proto3')
)

_PORTNUMBERS = _descriptor.EnumDescriptor(
  name='PortNumbers',
  full_name='ImageProcessorGrpc.PortNumbers',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unused', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CameraToVideoProcessorPort', index=1, number=28960,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=174,
  serialized_end=233,
)
_sym_db.RegisterEnumDescriptor(_PORTNUMBERS)

PortNumbers = enum_type_wrapper.EnumTypeWrapper(_PORTNUMBERS)
Unused = 0
CameraToVideoProcessorPort = 28960



_IMAGEBODY = _descriptor.Descriptor(
  name='ImageBody',
  full_name='ImageProcessorGrpc.ImageBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cameraId', full_name='ImageProcessorGrpc.ImageBody.cameraId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='ImageProcessorGrpc.ImageBody.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ImageProcessorGrpc.ImageBody.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='ImageProcessorGrpc.ImageBody.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='smallImageRGB', full_name='ImageProcessorGrpc.ImageBody.smallImageRGB', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=143,
)


_IMAGEREPLY = _descriptor.Descriptor(
  name='ImageReply',
  full_name='ImageProcessorGrpc.ImageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='ImageProcessorGrpc.ImageReply.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['ImageBody'] = _IMAGEBODY
DESCRIPTOR.message_types_by_name['ImageReply'] = _IMAGEREPLY
DESCRIPTOR.enum_types_by_name['PortNumbers'] = _PORTNUMBERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageBody = _reflection.GeneratedProtocolMessageType('ImageBody', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEBODY,
  '__module__' : 'ImageProcessorGrpc_pb2'
  # @@protoc_insertion_point(class_scope:ImageProcessorGrpc.ImageBody)
  })
_sym_db.RegisterMessage(ImageBody)

ImageReply = _reflection.GeneratedProtocolMessageType('ImageReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREPLY,
  '__module__' : 'ImageProcessorGrpc_pb2'
  # @@protoc_insertion_point(class_scope:ImageProcessorGrpc.ImageReply)
  })
_sym_db.RegisterMessage(ImageReply)



_GRPCCHANNEL = _descriptor.ServiceDescriptor(
  name='GrpcChannel',
  full_name='ImageProcessorGrpc.GrpcChannel',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=235,
  serialized_end=328,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubmitImage',
    full_name='ImageProcessorGrpc.GrpcChannel.SubmitImage',
    index=0,
    containing_service=None,
    input_type=_IMAGEBODY,
    output_type=_IMAGEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCCHANNEL)

DESCRIPTOR.services_by_name['GrpcChannel'] = _GRPCCHANNEL

# @@protoc_insertion_point(module_scope)
