# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'heoelri/demo-rating-mongodb'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/application/mongodb/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest