# Generated by Django 3.0.8 on 2020-08-28 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("locations", "0001_initial"), ("cameras", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.Location",
            ),
        )
    ]
