# Generated by Django 3.0.8 on 2020-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cameras", "0003_camera_lines")]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="danger_zones",
            field=models.CharField(blank=True, max_length=1000),
        )
    ]
