# Generated by Django 3.0.4 on 2020-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_auto_20200416_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_key', models.CharField(blank=True, max_length=1000)),
                ('endpoint', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
