# Generated by Django 3.0.7 on 2020-07-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='satisfaction',
            field=models.CharField(choices=[('VB', 'Very Bad'), ('PR', 'Poor'), ('FR', 'Fair'), ('GD', 'Good'), ('EX', 'Excellent')], default='FR', max_length=2),
        ),
    ]
