# Generated by Django 3.0.7 on 2020-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_satisfaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='satisfaction',
            field=models.CharField(choices=[('EX', 'Excellent'), ('GD', 'Good'), ('FR', 'Fair'), ('PR', 'Poor'), ('VB', 'Very Bad')], default='FR', max_length=2),
        ),
    ]
