# Generated by Django 3.0.7 on 2020-07-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200714_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='description',
        ),
    ]
