# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BoundingBoxProcessorGrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BoundingBoxProcessorGrpc.proto',
  package='BoundingBoxProcessorGrpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x42oundingBoxProcessorGrpc.proto\x12\x18\x42oundingBoxProcessorGrpc\"]\n\tImageData\x12\x10\n\x08\x63\x61meraId\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x13\n\x0bscoringData\x18\x05 \x01(\t\"/\n\nImageReply\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x12\n\nboxedImage\x18\x02 \x01(\x0c*@\n\x0bPortNumbers\x12\n\n\x06Unused\x10\x00\x12%\n\x1fImageProcessorToBoundingBoxPort\x10\xaa\xe2\x01\x32i\n\x0bGrpcChannel\x12Z\n\x0bSubmitImage\x12#.BoundingBoxProcessorGrpc.ImageData\x1a$.BoundingBoxProcessorGrpc.ImageReply\"\x00\x62\x06proto3')
)

_PORTNUMBERS = _descriptor.EnumDescriptor(
  name='PortNumbers',
  full_name='BoundingBoxProcessorGrpc.PortNumbers',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unused', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ImageProcessorToBoundingBoxPort', index=1, number=28970,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=204,
  serialized_end=268,
)
_sym_db.RegisterEnumDescriptor(_PORTNUMBERS)

PortNumbers = enum_type_wrapper.EnumTypeWrapper(_PORTNUMBERS)
Unused = 0
ImageProcessorToBoundingBoxPort = 28970



_IMAGEDATA = _descriptor.Descriptor(
  name='ImageData',
  full_name='BoundingBoxProcessorGrpc.ImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cameraId', full_name='BoundingBoxProcessorGrpc.ImageData.cameraId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='BoundingBoxProcessorGrpc.ImageData.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='BoundingBoxProcessorGrpc.ImageData.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='BoundingBoxProcessorGrpc.ImageData.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scoringData', full_name='BoundingBoxProcessorGrpc.ImageData.scoringData', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=153,
)


_IMAGEREPLY = _descriptor.Descriptor(
  name='ImageReply',
  full_name='BoundingBoxProcessorGrpc.ImageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='BoundingBoxProcessorGrpc.ImageReply.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boxedImage', full_name='BoundingBoxProcessorGrpc.ImageReply.boxedImage', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=202,
)

DESCRIPTOR.message_types_by_name['ImageData'] = _IMAGEDATA
DESCRIPTOR.message_types_by_name['ImageReply'] = _IMAGEREPLY
DESCRIPTOR.enum_types_by_name['PortNumbers'] = _PORTNUMBERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageData = _reflection.GeneratedProtocolMessageType('ImageData', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDATA,
  '__module__' : 'BoundingBoxProcessorGrpc_pb2'
  # @@protoc_insertion_point(class_scope:BoundingBoxProcessorGrpc.ImageData)
  })
_sym_db.RegisterMessage(ImageData)

ImageReply = _reflection.GeneratedProtocolMessageType('ImageReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREPLY,
  '__module__' : 'BoundingBoxProcessorGrpc_pb2'
  # @@protoc_insertion_point(class_scope:BoundingBoxProcessorGrpc.ImageReply)
  })
_sym_db.RegisterMessage(ImageReply)



_GRPCCHANNEL = _descriptor.ServiceDescriptor(
  name='GrpcChannel',
  full_name='BoundingBoxProcessorGrpc.GrpcChannel',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=270,
  serialized_end=375,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubmitImage',
    full_name='BoundingBoxProcessorGrpc.GrpcChannel.SubmitImage',
    index=0,
    containing_service=None,
    input_type=_IMAGEDATA,
    output_type=_IMAGEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCCHANNEL)

DESCRIPTOR.services_by_name['GrpcChannel'] = _GRPCCHANNEL

# @@protoc_insertion_point(module_scope)
