# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fpgagrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fpgagrpc.proto',
  package='FpgaGrpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x66pgagrpc.proto\x12\x08\x46pgaGrpc\"\x1a\n\tImageBody\x12\r\n\x05image\x18\x01 \x01(\x0c\"E\n\x0b\x42oundingBox\x12\x0c\n\x04xMin\x18\x01 \x01(\x01\x12\x0c\n\x04yMin\x18\x02 \x01(\x01\x12\x0c\n\x04xMax\x18\x03 \x01(\x01\x12\x0c\n\x04yMax\x18\x04 \x01(\x01\"b\n\nImageReply\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0f\n\x07\x63lasses\x18\x02 \x03(\x05\x12\x0e\n\x06scores\x18\x03 \x03(\x01\x12$\n\x05\x62oxes\x18\x04 \x03(\x0b\x32\x15.FpgaGrpc.BoundingBox*9\n\x0bPortNumbers\x12\n\n\x06Unused\x10\x00\x12\x1e\n\x18VideoProcessorToFpgaPort\x10\xa2\xe2\x01\x32M\n\x0f\x46pgaGrpcChannel\x12:\n\x0bSubmitImage\x12\x13.FpgaGrpc.ImageBody\x1a\x14.FpgaGrpc.ImageReply\"\x00\x62\x06proto3')
)

_PORTNUMBERS = _descriptor.EnumDescriptor(
  name='PortNumbers',
  full_name='FpgaGrpc.PortNumbers',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unused', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VideoProcessorToFpgaPort', index=1, number=28962,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=227,
  serialized_end=284,
)
_sym_db.RegisterEnumDescriptor(_PORTNUMBERS)

PortNumbers = enum_type_wrapper.EnumTypeWrapper(_PORTNUMBERS)
Unused = 0
VideoProcessorToFpgaPort = 28962



_IMAGEBODY = _descriptor.Descriptor(
  name='ImageBody',
  full_name='FpgaGrpc.ImageBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='FpgaGrpc.ImageBody.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=54,
)


_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='FpgaGrpc.BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xMin', full_name='FpgaGrpc.BoundingBox.xMin', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yMin', full_name='FpgaGrpc.BoundingBox.yMin', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xMax', full_name='FpgaGrpc.BoundingBox.xMax', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yMax', full_name='FpgaGrpc.BoundingBox.yMax', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=125,
)


_IMAGEREPLY = _descriptor.Descriptor(
  name='ImageReply',
  full_name='FpgaGrpc.ImageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='FpgaGrpc.ImageReply.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classes', full_name='FpgaGrpc.ImageReply.classes', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scores', full_name='FpgaGrpc.ImageReply.scores', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boxes', full_name='FpgaGrpc.ImageReply.boxes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=225,
)

_IMAGEREPLY.fields_by_name['boxes'].message_type = _BOUNDINGBOX
DESCRIPTOR.message_types_by_name['ImageBody'] = _IMAGEBODY
DESCRIPTOR.message_types_by_name['BoundingBox'] = _BOUNDINGBOX
DESCRIPTOR.message_types_by_name['ImageReply'] = _IMAGEREPLY
DESCRIPTOR.enum_types_by_name['PortNumbers'] = _PORTNUMBERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageBody = _reflection.GeneratedProtocolMessageType('ImageBody', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEBODY,
  __module__ = 'fpgagrpc_pb2'
  # @@protoc_insertion_point(class_scope:FpgaGrpc.ImageBody)
  ))
_sym_db.RegisterMessage(ImageBody)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDINGBOX,
  __module__ = 'fpgagrpc_pb2'
  # @@protoc_insertion_point(class_scope:FpgaGrpc.BoundingBox)
  ))
_sym_db.RegisterMessage(BoundingBox)

ImageReply = _reflection.GeneratedProtocolMessageType('ImageReply', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEREPLY,
  __module__ = 'fpgagrpc_pb2'
  # @@protoc_insertion_point(class_scope:FpgaGrpc.ImageReply)
  ))
_sym_db.RegisterMessage(ImageReply)



_FPGAGRPCCHANNEL = _descriptor.ServiceDescriptor(
  name='FpgaGrpcChannel',
  full_name='FpgaGrpc.FpgaGrpcChannel',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=286,
  serialized_end=363,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubmitImage',
    full_name='FpgaGrpc.FpgaGrpcChannel.SubmitImage',
    index=0,
    containing_service=None,
    input_type=_IMAGEBODY,
    output_type=_IMAGEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FPGAGRPCCHANNEL)

DESCRIPTOR.services_by_name['FpgaGrpcChannel'] = _FPGAGRPCCHANNEL

# @@protoc_insertion_point(module_scope)
