# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fpgagrpc_pb2 as fpgagrpc__pb2


class FpgaGrpcChannelStub(object):
  """FpgaGrpc service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubmitImage = channel.unary_unary(
        '/FpgaGrpc.FpgaGrpcChannel/SubmitImage',
        request_serializer=fpgagrpc__pb2.ImageBody.SerializeToString,
        response_deserializer=fpgagrpc__pb2.ImageReply.FromString,
        )


class FpgaGrpcChannelServicer(object):
  """FpgaGrpc service definition.
  """

  def SubmitImage(self, request, context):
    """Sends an image
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FpgaGrpcChannelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubmitImage': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitImage,
          request_deserializer=fpgagrpc__pb2.ImageBody.FromString,
          response_serializer=fpgagrpc__pb2.ImageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FpgaGrpc.FpgaGrpcChannel', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
