#FROM amd64/python:3.7-slim-buster
FROM nvcr.io/nvidia/tensorflow:19.12-tf1-py3
WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]