# Generated by Django 3.0.8 on 2020-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference_modules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencemodule",
            name="is_gpu",
            field=models.BooleanField(null=True),
        ),
    ]
