# Generated by Django 3.0.8 on 2020-08-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("azure_pd_deploy_status", "0002_auto_20200828_0616")]

    operations = [migrations.RemoveField(model_name="deploystatus", name="performance")]
