# Generated by Django 3.0.7 on 2020-07-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('azure_settings', '0001_initial'),
        ('azure_parts', '0001_initial'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customvision_project_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('customvision_project_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('download_uri', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('needRetraining', models.BooleanField(default=True)),
                ('training_counter', models.IntegerField(default=0)),
                ('is_demo', models.BooleanField(default=False)),
                ('deployed', models.BooleanField(default=False)),
                ('has_configured', models.BooleanField(default=False)),
                ('accuracyRangeMin', models.IntegerField(default=30)),
                ('accuracyRangeMax', models.IntegerField(default=80)),
                ('maxImages', models.IntegerField(default=20)),
                ('retraining_counter', models.IntegerField(default=0)),
                ('metrics_is_send_iothub', models.BooleanField(default=False)),
                ('metrics_accuracy_threshold', models.IntegerField(default=50)),
                ('metrics_frame_per_minutes', models.IntegerField(default=6)),
                ('prob_threshold', models.IntegerField(default=10)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.Camera')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('parts', models.ManyToManyField(related_name='part', to='azure_parts.Part')),
                ('setting', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='azure_settings.Setting')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('log', models.CharField(max_length=1000)),
                ('performance', models.CharField(default='{}', max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_training.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=200)),
                ('log', models.CharField(max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_training.Project')),
            ],
        ),
    ]
