# Generated by Django 3.0.7 on 2020-08-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='relabel_expired_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
