# Generated by Django 3.0.8 on 2020-08-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_training', '0002_project_relabel_expired_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='parts',
        ),
    ]
