# Generated by Django 3.0.8 on 2020-08-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azure_settings', '0001_initial'),
        ('azure_training', '0003_remove_project_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azure_settings.Setting'),
        ),
    ]
