# Generated by Django 3.0.8 on 2020-08-26 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("azure_settings", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customvision_id",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "download_uri",
                    models.CharField(
                        blank=True, default="", max_length=1000, null=True
                    ),
                ),
                ("training_counter", models.IntegerField(default=0)),
                ("is_demo", models.BooleanField(default=False)),
                ("maxImages", models.IntegerField(default=20)),
                (
                    "relabel_expired_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="azure_settings.Setting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_type", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=200)),
                ("log", models.CharField(max_length=1000)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="azure_projects.Project",
                    ),
                ),
            ],
        ),
    ]
