# Generated by Django 3.0.8 on 2020-08-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='needRetraining',
        ),
    ]
