# Generated by Django 3.0.8 on 2020-10-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camera_tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cameratask", old_name="cameras", new_name="camera",
        ),
    ]
