# Generated by Django 3.1.4 on 2021-02-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera_tasks", "0004_cameratask_enable_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="cameratask",
            name="counting_end_time",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cameratask",
            name="counting_start_time",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
