# Generated by Django 3.0.4 on 2020-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_project_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_uri',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
    ]
