# Generated by Django 3.0.4 on 2020-04-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_project_download_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='download_uri',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
