# Generated by Django 3.0.4 on 2020-04-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='endpoint',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='training_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
