# Generated by Django 3.0.4 on 2020-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_auto_20200427_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accuracyRangeMax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='accuracyRangeMin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='maxImages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='needRetraining',
            field=models.BooleanField(default=False),
        ),
    ]
