# Generated by Django 3.0.6 on 2020-05-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0010_auto_20200506_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('end_point', models.CharField(blank=True, default='', max_length=1000)),
                ('training_key', models.CharField(blank=True, default='', max_length=1000)),
                ('is_trainer_valid', models.BooleanField(default=False)),
                ('obj_detection_domain_id', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='project',
            name='training_key',
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('log', models.CharField(max_length=1000)),
                ('performance', models.CharField(default='{}', max_length=1000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='trainer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cameras.Trainer'),
            preserve_default=False,
        ),
    ]
