# Generated by Django 3.0.6 on 2020-05-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0011_auto_20200521_0655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainer',
            unique_together={('end_point', 'training_key')},
        ),
    ]
