# Generated by Django 3.0.4 on 2020-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0012_auto_20200522_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='area',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
