# Generated by Django 3.0.4 on 2020-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0013_camera_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='train_success_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='train_try_counter',
            field=models.IntegerField(default=0),
        ),
    ]
