# Generated by Django 3.0.4 on 2020-06-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0014_auto_20200529_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='trainer',
        ),
        migrations.AddField(
            model_name='project',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cameras.Setting'),
        ),
        migrations.AddField(
            model_name='setting',
            name='is_trainer_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='obj_detection_domain_id',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('endpoint', 'training_key')},
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
