# Generated by Django 3.0.4 on 2020-06-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0015_auto_20200603_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='remote_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name', 'is_demo')},
        ),
    ]
