# Generated by Django 3.0.4 on 2020-06-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0016_auto_20200604_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='is_collect_data',
            field=models.BooleanField(default=False),
        ),
    ]
