# Generated by Django 3.0.4 on 2020-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0018_auto_20200605_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='accuracyRangeMax',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='project',
            name='accuracyRangeMin',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='maxImages',
            field=models.IntegerField(default=10),
        ),
    ]
