# Generated by Django 3.0.4 on 2020-06-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0020_auto_20200610_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='train_success_counter',
            new_name='retraining_counter',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='train_try_counter',
            new_name='training_counter',
        ),
    ]
