# Generated by Django 3.0.7 on 2020-07-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0021_auto_20200617_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='project',
            name='setting',
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='train',
            name='project',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='model_name',
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
