name: ignite
channels:
  - defaults
dependencies:
  - blas=1.0
  - certifi=2019.6.16=py36_1
  - numpy=1.16.5
  - numpy-base=1.16.5
  - pip=19.2.2=py36_0
  - scipy=1.3.1
  - python=3.6.8
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_0
  - wheel=0.33.4=py36_0
  - flask=1.0.3
  - pip:
    - decorator==4.4.0
    - dlib==19.17.0
    - imageio==2.5.0
    - imutil==0.2.5
    - imutils==0.5.3
    - networkx==2.3
    - opencv-python==4.1.1.26
    - pillow==6.1.0
    - pywavelets==1.0.3
    - scikit-image==0.15.0
    - azure-iothub-device-client~=1.4.3
    - setuptools
    - ptvsd==4.1.3
    - onnxruntime==0.5.0
    - requests==2.20.1