# Generated by Django 3.0.8 on 2020-11-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inference_modules", "0003_auto_20200929_1042"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inferencemodule",
            name="is_gpu",
        ),
    ]
