# Generated by Django 3.0.8 on 2020-08-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azure_parts', '0001_initial'),
        ('images', '0002_image_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='azure_parts.Part'),
        ),
    ]
