# Generated by Django 3.0.8 on 2020-10-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_auto_20200902_0609"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="manual_checked",
            field=models.BooleanField(default=False),
        ),
    ]
