# Generated by Django 3.0.8 on 2021-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_manual_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='part_ids',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
