FROM intelligentedge/python3-opencv:py3.8.6-cv4.4.0.44-arm64v8

#RUN apt-get update && \
#    apt-get install -y --no-install-recommends \
#    libgl1-mesa-glx \
#    ffmpeg \
#    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY main.py .

EXPOSE 7000

CMD ["python", "main.py"]
