/**
 * Define all the action-export constants here.
 * TODO: Move the action export constant here.
 */

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';

export const DELETE_NOTIFICATION_REQUEST = 'DELETE_NOTIFICATION_REQUEST';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAILURE = 'DELETE_NOTIFICATION_FAILURE';

// Receive notifications from Websocket
export const RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION';

export const OPEN_NOTIFICATION_PANEL = 'OPEN_NOTIFICATION_PANEL';

export const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE';

export const POST_LOCATION_REQUEST = 'POST_LOCATION_REQUEST';
export const POST_LOCATION_SUCCESS = 'POST_LOCATION_SUCCESS';
export const POST_LOCATION_FAILURE = 'POST_LOCATION_FAILURE';

export const DELETE_LOCATION_REQUEST = 'DELETE_LOCATION_REQUEST';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_FAILURE = 'DELETE_LOCATION_FAILURE';

export const GET_PARTS_REQUEST = 'GET_PARTS_REQUEST';
export const GET_PARTS_SUCCESS = 'GET_PARTS_SUCCESS';
export const GET_PARTS_FAILURE = 'GET_PARTS_FAILURE';

export const POST_PART_REQUEST = 'POST_PART_REQUEST';
export const POST_PART_SUCCESS = 'POST_PART_SUCCESS';
export const POST_PART_FAILURE = 'POST_PART_FAILURE';

export const DELETE_PART_REQUEST = 'DELETE_PART_REQUEST';
export const DELETE_PART_SUCCESS = 'DELETE_PART_SUCCESS';
export const DELETE_PART_FAILURE = 'DELETE_PART_FAILURE';

export const PUT_PART_REQUEST = 'PUT_PART_REQUEST';
export const PUT_PART_SUCCESS = 'PUT_PART_SUCCESS';
export const PUT_PART_FAILURE = 'PUT_PART_FAILURE';

export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAILURE = 'GET_IMAGES_FAILURE';

export const CAPTURE_IMAGE_REQUEST = 'CAPTURE_IMAGE_REQUEST';
export const CAPTURE_IMAGE_SUCCESS = 'CAPTURE_IMAGE_SUCCESS';
export const CAPTURE_IMAGE_FAILURE = 'CAPTURE_IMAGE_FAILURE';