# Generated by Django 3.0.8 on 2020-08-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("azure_parts", "0001_initial"), ("azure_projects", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("labels", models.CharField(max_length=1000, null=True)),
                ("is_relabel", models.BooleanField(default=False)),
                ("confidence", models.FloatField(default=0.0)),
                ("uploaded", models.BooleanField(default=False)),
                (
                    "customvision_id",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("remote_url", models.CharField(max_length=1000, null=True)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="azure_parts.Part",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="azure_projects.Project",
                    ),
                ),
            ],
        )
    ]
