# Generated by Django 3.0.8 on 2020-09-02 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("azure_parts", "0001_initial"), ("images", "0002_image_camera")]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="part",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="azure_parts.Part",
            ),
        )
    ]
