# Generated by Django 3.0.8 on 2020-08-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("azure_projects", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="needRetraining",
            field=models.BooleanField(default=True),
        )
    ]
