# Generated by Django 3.0.8 on 2020-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("azure_projects", "0002_project_needretraining")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="retraining_counter",
            field=models.IntegerField(default=0),
        )
    ]
