# Generated by Django 3.0.8 on 2020-11-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azure_projects", "0003_project_retraining_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="download_uri_fp16",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
