# Generated by Django 3.0.8 on 2021-08-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_projects', '0005_auto_20201124_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
