# Generated by Django 3.0.8 on 2021-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_projects', '0006_auto_20210809_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='block_inputs',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='block_outputs',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_cascade',
            field=models.BooleanField(default=False),
        ),
    ]
