# Generated by Django 3.0.8 on 2021-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_projects', '0007_auto_20210811_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='node_type',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
