# Generated by Django 3.0.8 on 2021-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_projects', '0008_project_node_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='block_inputs',
            new_name='inputs',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='block_outputs',
            new_name='outputs',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='node_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='combined',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='demultiply_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='openvino_library_name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='openvino_model_name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='params',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
