# Generated by Django 3.0.8 on 2021-09-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_projects', '0011_remove_project_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='classification_type',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
