apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir-server
  template:
    metadata:
      labels:
        app: fhir-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: fhir-api
        image: {{ printf "healthplatformregistry.azurecr.io/%s_fhir-server:%s" .Values.fhir.version .Values.fhir.tag }}
        ports:
        - containerPort: {{ .Values.fhir.httpPort }}
          name: fhir-http
        - containerPort: {{ .Values.fhir.httpsPort }}
          name: fhir-https
        livenessProbe:
          httpGet: 
            scheme: HTTP
            path: /health/check
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
        envFrom:
        - secretRef:
            name: fhir-env
        volumeMounts:
        - name: fhir-server-certificate
          mountPath: /certs/certificate.pfx
          subPath: certificate.pfx
          readOnly: true
      volumes:
      - name: fhir-server-certificate
        secret:
          secretName: fhir-server-certificate
          items:
          - key: certificate
            path: certificate.pfx
